seo:
  site-name: The Sleep Co
  title: Default SEO Title
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
design:
  dark-text_color:
  medium-text_color:
  light-text_color:
  featured-text_color: '#ffbe00'
  dark_color:
  medium_color:
  light_color: '#e3ecf2'
  v-light_color: '#f9f9f9'
  featured_color: '#ffbe00'
  accent_color:
